use_frameworks!

target 'SwiftyHue_Example' do
  pod 'SwiftyHue', :path => '../'

  target 'SwiftyHue_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'Nocilla', '~> 0.10.0'
  end
end
